version: '3.9'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:80"
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
        - ./db_data:/var/opt/mssql/data
    ports:
      - "1433:1433"
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
